# Generated by Django 5.0.1 on 2024-02-27 19:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publishing_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
